### ISSUE TITLE
Dropout not assigned to the model for PyTorch Implementation of DeepFM

### ISSUE THREAD

**Issue by ywu94** [JianzhouZhan/RecommendationSystem#3]
In PyTorch Implementation of DeepFM `https://github.com/JianzhouZhan/Awesome-RecSystem-Models/blob/master/Model/DeepFM_PyTorch.py` the dropout layer for FM output assigned to the model in `__init__`. This causes inconsistency in evaluation.

**Comment by JianzhouZhan** [comment]
You are right!  I made a mistake. The dropout layer should not be used in evaluation!
