### ISSUE TITLE
类别型特征处理

### ISSUE THREAD

**Issue by zhangatao** [JianzhouZhan/RecommendationSystem#4]
![image](https://user-images.githubusercontent.com/28706321/92884017-09f18c80-f444-11ea-8195-58fa533177ab.png)
你好，为什么处理类别型特征要这样处理，为啥不进行label_encoder处理
还有计算fm的时候，下面是什么意思，可以解释一下吗，为啥要用到feat_index
![image](https://user-images.githubusercontent.com/28706321/92884298-491fdd80-f444-11ea-8a17-aadccec49f1f.png)

**Comment by JianzhouZhan** [comment]
类别型特征的处理以及feat_index的使用, 都是为了做Embedding, label_encoder是对特征进行硬编码, 在这里并不适用
