### ISSUE TITLE
下载路径出错

### ISSUE THREAD

**Issue by Y-ZZH** [JianzhouZhan/RecommendationSystem#5]
您好，请问下“train.txt”文件下载路径是换了嘛？

**Comment by aoqun** [comment]
十分感谢您的来信，我会尽快查阅。祝好！O(∩_∩)O

**Comment by oohh2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的来信已收到！！！

**Comment by redcattle** [comment]
Hello, can you post the download path of the "train.txt" file? The original path cannot be downloaded. Thanks!

**Comment by weiucas** [comment]
Hello, the url of "train.txt" is not exist, can you post the new download path?

**Comment by oohh2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的来信已收到！！！

**Comment by aoqun** [comment]
十分感谢您的来信，我会尽快查阅。祝好！O(∩_∩)O
